#!/bin/bash

if [ -z "$KAVRAKILAB_ROS_DISTRO" ]
then
    echo "[tue ros setup] KAVRAKILAB_ROS_DISTRO was not set"
    return
fi

#source /opt/ros/$KAVRAKILAB_ROS_DISTRO/setup.bash

KAVRAKILAB_SYSTEM_DIR=$KAVRAKILAB_ENV_DIR/system
KAVRAKILAB_DEV_DIR=$KAVRAKILAB_ENV_DIR/dev

source $KAVRAKILAB_DEV_DIR/devel/setup.bash
